name: Otus homework tests

on:
  push:
    branches:
      - hw*

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, 'calendar') }}
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.19

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
          working-directory: ${{ env.BRANCH }}

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: pwd
        run: pwd
        working-directory: ${{ env.BRANCH }}

      - name: Bash tests
        shell: bash
        run: ./test.sh
        working-directory: ${{ env.BRANCH }}

